---
platform: linux

inputs:
- name: platform-automation-tasks
- name: state # contains the state for the vm
- name: config # contains the product configuration file
- name: vars # variable files to be made available
  optional: true
- name: secrets
  # secret files to be made available
  # separate from vars, so they can be store securely
  optional: true

outputs:
- name: generated-state #contains the updated state file

params:
  VARS_FILES:
  # - Optional
  # - Filepath to the Ops Manager vars yaml file
  # - The path is relative to root of the task build,
  #   so `vars` and `secrets` can be used.

  OPSMAN_CONFIG_FILE: opsman.yml
  # - Required
  # - Filepath of the opsman config YAML
  # - The path is relative to root of the `config` input

  STATE_FILE: state.yml
  # - Required
  # - Filepath of the state yaml file
  # - The path is relative to root of the `state` output
  # - if the filename includes "$timestamp",
  #   for example "state-$timestamp.yml",
  #   the final filename will include the current timestamp.
  #   - this is necessary if using an "S3 compatible" blobstore
  #     that doesn't support versioned blobs
  #   - timestamped filenames will need to be represented
  #     with a glob-style wildcard in tasks that use this state file
  #     (such as state-*.yml)

  IAAS_TYPE:
  # - Required
  # - detects whether installation is vsphere

  OM_VARS_ENV: OM_VAR
  # Used by the wrapper script
  OM_VAR_decryption_passphrase: none
  # Used to allow the env file to be interpolated, but not needed
  OM_VAR_om_login:
  # Used by the wrapper script to check if the deployment was removed
  OM_VAR_domain:
  # Used by the wrapper script to check if the deployment was removed
  OM_VAR_cloud_creds:

run:
  path: config/tasks/wrapper-delete-vm/task.sh